### ISSUE TITLE
Get Price from Vol

### ISSUE THREAD

**Issue by topchatz** [vollib/py_vollib#12]
Hi guys, big fan of Vollib, I was wondering though is there a way to get say the options price from the implied vol? I basically now have my cubic spline going through the bid/ask mids but want to see in Price terms how under/over valued out of line strikes are.

Cheers

**Comment by lbrichards** [comment]
This is how you would do it with [Black](http://www.vollib.org/documentation/python/1.0.2/apidoc/py_vollib.black.html#py_vollib.black.black) (from the docs).

```
>>> F = 100
>>> K = 100
>>> sigma = .2
>>> flag = 'c'
>>> r = .02
>>> t = .5
>>> black(flag, F, K, t, r, sigma)
5.5811067246048118
```
black_scholes and black_scholes_merton modules each have analogous functions.
