### ISSUE TITLE
Boundary condiiton error

### ISSUE THREAD

**Issue by evelynmitchell** [vollib/py_vollib#16]
via: https://twitter.com/TheSpeculator0/status/1403880012831498240
 the arbitrage boundary conditions are slightly wrong for the black76 version. Does not take funding of premium into account when looking at "intrinsic"

**Comment by lbrichards** [comment]
Here you can see all about Jaeckel's implementation of Black76 which is the core of vollib: http://www.jaeckel.org/LetsBeRational.pdf
