### ISSUE TITLE
How to use this lib?

### ISSUE THREAD

**Issue by kramer65** [vollib/py_vollib#3]
I manually installed this package on OSX (`sudo python setup.py install`), but after importing it I don't see any usefull methods or classes in there:
```
>>> import py_vollib
>>> dir(py_vollib)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__']
```

I also checked out [the docs](http://www.vollib.org/documentation/python/1.0.2/) but it only mentions things about installation and performance, nothing about how to actually use this lib.

Does anybody know how I can calculate an option price and get it's greeks using vollib?

**Comment by bstemper** [comment]
The code is actually well documented. Say you want to compute the Black-Scholes delta of an option, then look into py_vollib/py_vollib/black_scholes/greeks/analytical.py and find the delta function etc.

**Comment by lbrichards** [comment]
Check out the doctests!
