### ISSUE TITLE
Do you have any plans adding a SABR model?

### ISSUE THREAD

**Issue by stnatter** [vollib/py_vollib#4]
SABR is an extension of Black76 adding a stochastic volatility process. Shifted or zero boundary SABR models which allow pricing of negative strikes are the standard for Interest Rate options nowadays.
https://www.google.com.hk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwjN5YSJs8rWAhXMU7wKHU54BEwQFggtMAE&url=http%3A%2F%2Fwww.next-finance.net%2FIMG%2Fpdf%2Fpdf_SABR.pdf&usg=AFQjCNFSBx3WXmbPG2yONaVTwrEK9BFZ5Q

**Comment by lbrichards** [comment]
We have no plans at present, but thank you for the suggestion and reference.
