### ISSUE TITLE
Very slow to run on SQL Server 2017

### ISSUE THREAD

**Issue by YizeD** [vollib/py_vollib#8]
I am trying to run some calculations on SQL Server by sending the calculations to server from python scripts. When I try to run sample calculations on my local machine, it takes less than a second to run sample calculations. When I try to run it on the SQL server, however, it takes a long time. It seems like the server has trouble importing modules. Specifically, when I add this line to the code

`from py_vollib.black_scholes.implied_volatility import implied_volatility as iv`

the server will take forever to run the script, even if I never make any calls to iv.

When I check the packages in the server, all the required packages for py_vollib (including numba) are installed. Any idea as to what might be causing the problem?

**Comment by lbrichards** [comment]
Using any kind of SQL Server is outside the scope of this project.
